[package]
name = "yunxi-plugin-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
yunxi-kernel = { path = "../yunxi-kernel" }
yunxi-protocol = { path = "../yunxi-protocol" }
yunxi-secret-broker = { path = "../yunxi-secret-broker" }

[lints]
workspace = true
