#![doc = "Bounded Web Gateway facade with optional durable event replay for YunXi Next."]
#![forbid(unsafe_code)]

mod assets;
mod dispatch;
mod error;
mod events;
mod http;
mod projection;
mod sse;

pub use dispatch::{
    AGENT_PRESET_LIST_METHOD, COMMANDS_LIST_METHOD, CREDENTIALS_DESCRIBE_METHOD,
    DYNAMIC_CORDIS_INVENTORY_METHOD, DYNAMIC_CORDIS_SYNC_INSPECT_METHOD, Gateway, GatewayBackend,
    HEALTH_STATUS_METHOD, HOST_DESCRIBE_METHOD, LLM_PROVIDERS_METHOD, MAILBOX_GET_METHOD,
    MAILBOX_LIST_METHOD, MAILBOX_MARK_READ_METHOD, MEMORY_LIST_METHOD, MEMORY_SHOW_METHOD,
    MEMORY_STATUS_METHOD, PERSONA_LIST_METHOD, PERSONA_PROFILE_METHOD, PERSONA_STATUS_METHOD,
    PLUGIN_INVENTORY_LIST_METHOD, RELATIONSHIP_LIST_METHOD, RELATIONSHIP_STATUS_METHOD,
    SESSION_ATTACHMENT_METHOD, SESSION_CANCEL_METHOD, SESSION_CREATE_METHOD, SESSION_FORK_METHOD,
    SESSION_HISTORY_METHOD, SESSION_LIST_METHOD, SESSION_MODELS_METHOD, SESSION_PROMPT_METHOD,
    SESSION_RENAME_METHOD, SESSION_SEARCH_METHOD, SESSION_SELECT_MODEL_METHOD,
    SESSION_UPDATE_QUEUE_METHOD, SETTINGS_DESCRIBE_METHOD, SETTINGS_MUTATE_METHOD,
    SETTINGS_REPLACE_METHOD, SETTINGS_UPDATE_METHOD, SKILL_LIST_METHOD, SUBAGENT_HISTORY_METHOD,
    SUBAGENT_INTERRUPT_METHOD, SUBAGENT_LIST_METHOD, SUBAGENT_PROMPT_METHOD, VOICE_CANCEL_METHOD,
    VOICE_CHAT_METHOD, VOICE_DEVICES_METHOD, VOICE_DOCTOR_METHOD, VOICE_PLAYBACK_METHOD,
    VOICE_SAVE_METHOD, VOICE_SPEAK_METHOD, VOICE_TALK_METHOD, VOICE_TRANSCRIBE_METHOD,
    WEIXIN_CONTROL_METHOD, WEIXIN_DOCTOR_METHOD, WEIXIN_LOGIN_METHOD, WEIXIN_LOGOUT_METHOD,
    WEIXIN_PAIR_METHOD, WEIXIN_POLL_LOGIN_METHOD, WEIXIN_QUEUED_METHOD, WEIXIN_REPLY_METHOD,
    WEIXIN_SEND_METHOD, WEIXIN_SERVE_METHOD, WEIXIN_SERVE_START_METHOD, WEIXIN_SERVE_STATUS_METHOD,
    WEIXIN_SERVE_STOP_METHOD, WEIXIN_SESSION_METHOD, WEIXIN_STATUS_METHOD, WORKSPACE_LIST_METHOD,
};
pub use error::GatewayError;
pub use events::{
    EventJournal, EventJournalError, MAX_PENDING_EVENTS, MAX_PERSISTED_EVENT_LOG_BYTES,
    MAX_PERSISTED_EVENT_RECORD_BYTES, MAX_REPLAY_BYTES,
};
pub use http::{
    DEFAULT_HTTP_READ_TIMEOUT, HttpCarrier, HttpParseError, HttpRequest, HttpResponse,
    MAX_HTTP_BODY_BYTES, MAX_HTTP_CONNECTION_WORKERS, MAX_HTTP_HEADER_BYTES,
    MAX_HTTP_RESPONSE_BYTES, MAX_HTTP_WRITE_TIMEOUT, MAX_SSE_LONG_POLL, MAX_WEB_ASSET_BYTES,
    ShutdownToken,
};
pub use projection::{GatewayProjection, GatewaySessionSummary, GatewayStatus};
pub use sse::{MAX_SSE_EVENTS, MAX_SSE_RESPONSE_BYTES};
