[package]
name = "yunxi-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
yunxi-kernel = { path = "../yunxi-kernel" }
yunxi-model-openai = { path = "../yunxi-model-openai" }
yunxi-protocol = { path = "../yunxi-protocol" }

[[bin]]
name = "yunxi"
path = "src/main.rs"

[lints]
workspace = true
