//! Host-issued network scopes and secret references.
//!
//! These contracts deliberately contain authority descriptions only. Secret
//! values stay in the process that owns the secret store and never cross the
//! YunXi plugin protocol.

use std::error::Error;
use std::fmt;

use serde::de::Error as _;
use serde::{Deserialize, Deserializer, Serialize};

pub const MAX_NETWORK_SCOPES: usize = 32;
pub const MAX_NETWORK_HOST_BYTES: usize = 253;
pub const MAX_SECRET_REFERENCES: usize = 32;
pub const MAX_SECRET_REFERENCE_BYTES: usize = 128;

/// Schemes understood by the bounded MCP network authority.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum NetworkScheme {
    Http,
    Https,
}

impl NetworkScheme {
    pub const fn default_port(self) -> u16 {
        match self {
            Self::Http => 80,
            Self::Https => 443,
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Http => "http",
            Self::Https => "https",
        }
    }
}

impl fmt::Display for NetworkScheme {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// One exact scheme/host/port network permission.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct NetworkScope {
    scheme: NetworkScheme,
    host: String,
    port: u16,
}

impl NetworkScope {
    pub fn new(
        scheme: NetworkScheme,
        host: impl Into<String>,
        port: Option<u16>,
    ) -> Result<Self, AuthorityError> {
        let host = normalize_host(&host.into())?;
        Ok(Self {
            scheme,
            host,
            port: port.unwrap_or_else(|| scheme.default_port()),
        })
    }

    /// Creates a scope from an endpoint URL, ignoring its path.
    pub fn from_url(url: &str) -> Result<Self, AuthorityError> {
        let (scheme, host, port) = parse_endpoint(url)?;
        Self::new(scheme, host, Some(port))
    }

    pub const fn scheme(&self) -> NetworkScheme {
        self.scheme
    }

    pub fn host(&self) -> &str {
        &self.host
    }

    pub const fn port(&self) -> u16 {
        self.port
    }

    pub fn matches_url(&self, url: &str) -> bool {
        parse_endpoint(url)
            .map(|(scheme, host, port)| {
                scheme == self.scheme && host == self.host && port == self.port
            })
            .unwrap_or(false)
    }

    fn validate(&self) -> Result<(), AuthorityError> {
        if self.port == 0 {
            return Err(AuthorityError::InvalidPort);
        }
        normalize_host(&self.host).map(|_| ())
    }
}

impl<'de> Deserialize<'de> for NetworkScope {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct WireScope {
            scheme: NetworkScheme,
            host: String,
            port: u16,
        }

        let wire = WireScope::deserialize(deserializer)?;
        Self::new(wire.scheme, wire.host, Some(wire.port)).map_err(D::Error::custom)
    }
}

/// A set of exact network scopes. `allow_any` exists only for legacy
/// low-level callers and is intentionally not generated by the CLI.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct NetworkGrant {
    scopes: Vec<NetworkScope>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    allow_any: bool,
}

impl NetworkGrant {
    pub fn new(scopes: Vec<NetworkScope>) -> Result<Self, AuthorityError> {
        let grant = Self {
            scopes,
            allow_any: false,
        };
        grant.validate()?;
        Ok(grant)
    }

    pub fn for_url(url: &str) -> Result<Self, AuthorityError> {
        Self::new(vec![NetworkScope::from_url(url)?])
    }

    pub fn unrestricted() -> Self {
        Self {
            scopes: Vec::new(),
            allow_any: true,
        }
    }

    pub fn none() -> Self {
        Self {
            scopes: Vec::new(),
            allow_any: false,
        }
    }

    pub fn scopes(&self) -> &[NetworkScope] {
        &self.scopes
    }

    pub const fn is_unrestricted(&self) -> bool {
        self.allow_any
    }

    pub fn is_empty(&self) -> bool {
        self.scopes.is_empty() && !self.allow_any
    }

    pub fn allows_url(&self, url: &str) -> bool {
        self.allow_any || self.scopes.iter().any(|scope| scope.matches_url(url))
    }

    pub fn validate(&self) -> Result<(), AuthorityError> {
        if self.scopes.len() > MAX_NETWORK_SCOPES {
            return Err(AuthorityError::TooManyNetworkScopes {
                count: self.scopes.len(),
                maximum: MAX_NETWORK_SCOPES,
            });
        }
        for scope in &self.scopes {
            scope.validate()?;
        }
        let mut seen = std::collections::BTreeSet::new();
        for scope in &self.scopes {
            if !seen.insert(scope) {
                return Err(AuthorityError::DuplicateNetworkScope {
                    host: scope.host.clone(),
                    port: scope.port,
                });
            }
        }
        Ok(())
    }
}

impl Default for NetworkGrant {
    fn default() -> Self {
        Self::none()
    }
}

impl<'de> Deserialize<'de> for NetworkGrant {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct WireGrant {
            #[serde(default)]
            scopes: Vec<NetworkScope>,
            #[serde(default)]
            allow_any: bool,
        }

        let wire = WireGrant::deserialize(deserializer)?;
        let grant = Self {
            scopes: wire.scopes,
            allow_any: wire.allow_any,
        };
        grant.validate().map_err(D::Error::custom)?;
        Ok(grant)
    }
}

/// References to secrets that a Host has explicitly made available.
///
/// This type never contains the referenced values.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize)]
pub struct SecretGrant {
    references: Vec<String>,
}

impl SecretGrant {
    pub fn new(references: Vec<String>) -> Result<Self, AuthorityError> {
        let grant = Self { references };
        grant.validate()?;
        Ok(grant)
    }

    pub fn one(reference: impl Into<String>) -> Result<Self, AuthorityError> {
        Self::new(vec![reference.into()])
    }

    pub fn empty() -> Self {
        Self::default()
    }

    pub fn references(&self) -> &[String] {
        &self.references
    }

    pub fn allows(&self, reference: &str) -> bool {
        self.references.iter().any(|value| value == reference)
    }

    pub fn is_empty(&self) -> bool {
        self.references.is_empty()
    }

    pub fn validate(&self) -> Result<(), AuthorityError> {
        if self.references.len() > MAX_SECRET_REFERENCES {
            return Err(AuthorityError::TooManySecretReferences {
                count: self.references.len(),
                maximum: MAX_SECRET_REFERENCES,
            });
        }
        let mut seen = std::collections::BTreeSet::new();
        for reference in &self.references {
            validate_reference(reference)?;
            if !seen.insert(reference) {
                return Err(AuthorityError::DuplicateSecretReference {
                    reference: reference.clone(),
                });
            }
        }
        Ok(())
    }
}

impl<'de> Deserialize<'de> for SecretGrant {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct WireGrant {
            #[serde(default)]
            references: Vec<String>,
        }

        let wire = WireGrant::deserialize(deserializer)?;
        Self::new(wire.references).map_err(D::Error::custom)
    }
}

fn normalize_host(value: &str) -> Result<String, AuthorityError> {
    if value.trim().is_empty() {
        return Err(AuthorityError::EmptyNetworkHost);
    }
    if value.len() > MAX_NETWORK_HOST_BYTES {
        return Err(AuthorityError::NetworkHostTooLong {
            length: value.len(),
            maximum: MAX_NETWORK_HOST_BYTES,
        });
    }
    if value
        .chars()
        .any(|character| character.is_control() || character.is_whitespace())
    {
        return Err(AuthorityError::InvalidNetworkHost {
            host: value.to_string(),
        });
    }
    let value = value.trim_end_matches('.').to_ascii_lowercase();
    if value.is_empty()
        || value.contains('/')
        || value.contains('@')
        || value.contains('?')
        || value.contains('#')
    {
        return Err(AuthorityError::InvalidNetworkHost { host: value });
    }
    if value.starts_with('[') || value.ends_with(']') {
        return Err(AuthorityError::InvalidNetworkHost { host: value });
    }
    if !value
        .chars()
        .all(|character| character.is_ascii_alphanumeric() || matches!(character, '.' | '-' | ':'))
    {
        return Err(AuthorityError::InvalidNetworkHost { host: value });
    }
    Ok(value)
}

fn parse_endpoint(url: &str) -> Result<(NetworkScheme, String, u16), AuthorityError> {
    if url
        .chars()
        .any(|character| character.is_control() || character.is_whitespace())
    {
        return Err(AuthorityError::InvalidEndpoint {
            endpoint: url.to_string(),
        });
    }
    let (scheme, remainder) =
        url.split_once("://")
            .ok_or_else(|| AuthorityError::InvalidEndpoint {
                endpoint: url.to_string(),
            })?;
    let scheme = match scheme.to_ascii_lowercase().as_str() {
        "http" => NetworkScheme::Http,
        "https" => NetworkScheme::Https,
        _ => {
            return Err(AuthorityError::UnsupportedNetworkScheme {
                scheme: scheme.to_string(),
            });
        }
    };
    let authority_end = remainder.find(['/', '?', '#']).unwrap_or(remainder.len());
    let authority = &remainder[..authority_end];
    if authority.is_empty() || authority.contains('@') {
        return Err(AuthorityError::InvalidEndpoint {
            endpoint: url.to_string(),
        });
    }

    let (host, port) = if let Some(stripped) = authority.strip_prefix('[') {
        let Some((host, remainder)) = stripped.split_once(']') else {
            return Err(AuthorityError::InvalidEndpoint {
                endpoint: url.to_string(),
            });
        };
        let port = if remainder.is_empty() {
            scheme.default_port()
        } else if let Some(port) = remainder.strip_prefix(':') {
            parse_port(port, url)?
        } else {
            return Err(AuthorityError::InvalidEndpoint {
                endpoint: url.to_string(),
            });
        };
        (host.to_string(), port)
    } else if let Some((host, port)) = authority.rsplit_once(':') {
        if port.is_empty() || !port.chars().all(|character| character.is_ascii_digit()) {
            return Err(AuthorityError::InvalidEndpoint {
                endpoint: url.to_string(),
            });
        }
        (host.to_string(), parse_port(port, url)?)
    } else {
        (authority.to_string(), scheme.default_port())
    };

    Ok((scheme, normalize_host(&host)?, port))
}

fn parse_port(value: &str, endpoint: &str) -> Result<u16, AuthorityError> {
    let port = value
        .parse::<u16>()
        .map_err(|_| AuthorityError::InvalidEndpoint {
            endpoint: endpoint.to_string(),
        })?;
    if port == 0 {
        return Err(AuthorityError::InvalidPort);
    }
    Ok(port)
}

fn validate_reference(value: &str) -> Result<(), AuthorityError> {
    if value.trim().is_empty() {
        return Err(AuthorityError::EmptySecretReference);
    }
    if value.len() > MAX_SECRET_REFERENCE_BYTES {
        return Err(AuthorityError::SecretReferenceTooLong {
            length: value.len(),
            maximum: MAX_SECRET_REFERENCE_BYTES,
        });
    }
    if !value.chars().all(|character| {
        character.is_ascii_alphanumeric() || matches!(character, '.' | '_' | '-' | ':' | '/')
    }) {
        return Err(AuthorityError::InvalidSecretReference {
            reference: value.to_string(),
        });
    }
    if !value
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_alphanumeric())
    {
        return Err(AuthorityError::InvalidSecretReference {
            reference: value.to_string(),
        });
    }
    Ok(())
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum AuthorityError {
    EmptyNetworkHost,
    NetworkHostTooLong { length: usize, maximum: usize },
    InvalidNetworkHost { host: String },
    UnsupportedNetworkScheme { scheme: String },
    InvalidEndpoint { endpoint: String },
    InvalidPort,
    TooManyNetworkScopes { count: usize, maximum: usize },
    DuplicateNetworkScope { host: String, port: u16 },
    EmptySecretReference,
    SecretReferenceTooLong { length: usize, maximum: usize },
    InvalidSecretReference { reference: String },
    TooManySecretReferences { count: usize, maximum: usize },
    DuplicateSecretReference { reference: String },
}

impl fmt::Display for AuthorityError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyNetworkHost => formatter.write_str("network host cannot be empty"),
            Self::NetworkHostTooLong { length, maximum } => {
                write!(
                    formatter,
                    "network host is {length} bytes; maximum is {maximum}"
                )
            }
            Self::InvalidNetworkHost { host } => {
                write!(formatter, "network host `{host}` is invalid")
            }
            Self::UnsupportedNetworkScheme { scheme } => {
                write!(formatter, "network scheme `{scheme}` is unsupported")
            }
            Self::InvalidEndpoint { endpoint } => {
                write!(formatter, "network endpoint `{endpoint}` is invalid")
            }
            Self::InvalidPort => formatter.write_str("network port must be between 1 and 65535"),
            Self::TooManyNetworkScopes { count, maximum } => write!(
                formatter,
                "network grant contains {count} scopes; maximum is {maximum}"
            ),
            Self::DuplicateNetworkScope { host, port } => {
                write!(formatter, "network grant repeats `{host}:{port}`")
            }
            Self::EmptySecretReference => formatter.write_str("secret reference cannot be empty"),
            Self::SecretReferenceTooLong { length, maximum } => write!(
                formatter,
                "secret reference is {length} bytes; maximum is {maximum}"
            ),
            Self::InvalidSecretReference { reference } => {
                write!(formatter, "secret reference `{reference}` is invalid")
            }
            Self::TooManySecretReferences { count, maximum } => write!(
                formatter,
                "secret grant contains {count} references; maximum is {maximum}"
            ),
            Self::DuplicateSecretReference { reference } => {
                write!(formatter, "secret grant repeats `{reference}`")
            }
        }
    }
}

impl Error for AuthorityError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn endpoint_scopes_match_only_the_exact_authority() {
        let scope = NetworkScope::from_url("https://api.example.test/v1").expect("scope");
        let grant = NetworkGrant::new(vec![scope]).expect("grant");
        assert!(grant.allows_url("https://api.example.test/other"));
        assert!(!grant.allows_url("http://api.example.test/v1"));
        assert!(!grant.allows_url("https://other.example.test/v1"));
        assert!(!grant.allows_url("https://api.example.test:8443/v1"));
    }

    #[test]
    fn authority_wire_contains_scopes_and_references_but_no_values() {
        let network = NetworkGrant::for_url("https://api.example.test").expect("network grant");
        let secret = SecretGrant::one("provider/openai/api_key").expect("secret grant");
        let json = serde_json::to_string(&(network, secret)).expect("serialize authority");
        assert!(json.contains("api.example.test"));
        assert!(json.contains("provider/openai/api_key"));
        assert!(!json.contains("sk-secret-value"));
    }

    #[test]
    fn malformed_authority_is_rejected_on_decode() {
        let error = serde_json::from_str::<NetworkGrant>(
            r#"{"scopes":[{"scheme":"https","host":"api.example.test","port":0}]}"#,
        )
        .expect_err("zero port must fail");
        assert!(error.to_string().contains("port"));

        let error = serde_json::from_str::<SecretGrant>(r#"{"references":["bad secret"]}"#)
            .expect_err("invalid reference must fail");
        assert!(error.to_string().contains("secret reference"));
    }
}
